# Generated by Django 3.0 on 2020-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201120_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ritarget',
            fields=[
                ('ztime', models.DateTimeField(blank=True, null=True)),
                ('zutime', models.DateTimeField(blank=True, null=True)),
                ('zid', models.IntegerField(blank=True, null=True)),
                ('xdate', models.DateField(blank=True, null=True)),
                ('xrow', models.IntegerField(primary_key=True, serialize=False)),
                ('xziid', models.CharField(blank=True, max_length=50, null=True)),
                ('xtsoid', models.CharField(blank=True, max_length=50, null=True)),
                ('xriid', models.CharField(blank=True, max_length=50, null=True)),
                ('xzone', models.CharField(blank=True, max_length=100, null=True)),
                ('xdiv', models.CharField(blank=True, max_length=100, null=True)),
                ('xqty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('zemail', models.CharField(blank=True, max_length=100, null=True)),
                ('xemail', models.CharField(blank=True, max_length=100, null=True)),
                ('xyear', models.IntegerField(blank=True, null=True)),
                ('xper', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Ritarget',
                'managed': False,
            },
        ),
    ]
